# Generated by Django 3.2 on 2021-11-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vagas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagas',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
