# Generated by Django 3.2 on 2021-11-26 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vagas', '0001_initial'),
        ('Curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='vaga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curriculos_vaga', to='Vagas.vagas'),
        ),
    ]
